services:
  crypto_checker_bot:
    restart: always
    container_name: "crypto_checker_bot"
    build: .
    entrypoint: /start.sh
    environment:
      - BOT_TOKEN=
      - ADMINS=
      - DB_HOST=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_DATABASE=