"""init

Revision ID: fdc6598b6b70
Revises:
Create Date: 2024-09-28 03:13:43.566029

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fdc6598b6b70"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("percent", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__users")),
    )
    op.create_table(
        "crypto_pairs",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("price", sa.Numeric(precision=16, scale=8), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("crypto_pairs_user_id_fkey")),
        sa.PrimaryKeyConstraint("name", "user_id", name=op.f("pk__crypto_pairs")),
    )
    op.create_index(op.f("ix__crypto_pairs_user_id"), "crypto_pairs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__crypto_pairs_user_id"), table_name="crypto_pairs")
    op.drop_table("crypto_pairs")
    op.drop_table("users")
    # ### end Alembic commands ###
