name: Lint

on: [ push, pull_request ]

jobs:
  black:
    name: Black Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check"
          src: "./crypto_checker"
          use_pyproject: "true"

  flake8:
    runs-on: ubuntu-latest
    name: Flake8 Lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          pip install flake8==7.1.1
          flake8 ./crypto_checker